/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2015-08-08 14:46:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class quotation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>Arbutus Quotation Master</title>\r\n");
      out.write("   <script src=\"jquery.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <link rel=\"stylesheet\" href=\"jquery-ui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"jquery-ui.structure.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"jquery-ui.theme.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"jquery-ui.min.css\">\r\n");
      out.write("  \r\n");
      out.write("   <script src=\"jquery-ui.js\"></script>\r\n");
      out.write("   <script src=\"jquery-ui.min.js\"></script>\r\n");
      out.write("  <script  src=\"arbutusScripts.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("  $(function() {\r\n");
      out.write("    $( \"#tabs\" ).tabs();\r\n");
      out.write("    getData();   \r\n");
      out.write("    //alert(availableTags);\r\n");
      out.write("  });\r\n");
      out.write("  </script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  i=2;\r\n");
      out.write("  function addRows()\r\n");
      out.write("  {\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t$('#myTable').append('<tr id=\"Row'+i+'\"><td><input type=\"text\" value='+i+' style=\"width:90px\"></td><td><input type=\"text\" class=\"partFill\" style=\"width:180px\"></td><td><input type=\"text\" ></td><td><input type=\"text\" autocomplete=\"off\" class=\"makeFill\" onfocus=\"populates()\" style=\"width:180px\"></td><td><input type=\"text\" style=\"width:180px\"></td><td><input type=\"text\" style=\"width:150px\"></td><td><input type=\"text\" style=\"width:150px\"></td><td><input type=\"text\" style=\"width:150px\"></td><td><input type=\"text\" style=\"width:150px\"></td>');\r\n");
      out.write("\t    \r\n");
      out.write("\ti++;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  function deleteRows()\r\n");
      out.write("  {\r\n");
      out.write("\t  --i;\r\n");
      out.write("\t  $('#Row'+i).remove();\r\n");
      out.write("\t \r\n");
      out.write("\t  if(i==1)\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t\t  i=2;\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t \r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" \r\n");
      out.write("<div id=\"tabs\">\r\n");
      out.write("  <ul>\r\n");
      out.write("    <li><a href=\"#tabs-1\">Create Quotation</a></li>\r\n");
      out.write("    <li><a href=\"#tabs-2\">Insert Customer</a></li>\r\n");
      out.write("    <li><a href=\"#tabs-3\">Insert Part</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  <div id=\"tabs-1\">\r\n");
      out.write("  <table>\r\n");
      out.write("   <tr>\r\n");
      out.write("   <td>Quotation Number</td><td><input type=\"text\" value=\"AR-\" id=\"qtn_num\"></td></tr>\r\n");
      out.write("   <tr><td>Company Name</td><td><input type=\"text\" id=\"company_name\"></td><td><input type=\"button\" value=\"search\" onclick=\"findCompany()\"></td></tr>\r\n");
      out.write("   <tr><td>Address</td><td><textarea rows=\"5\" id=\"address\"></textarea></td></tr>\r\n");
      out.write("  \t<tr><td>Customer Name</td><td><input type=\"text\" id=\"name\"></td></tr>\r\n");
      out.write("   <tr><td>Subject</td><td><input type=\"text\" id=\"subject\"></td><td></td><td>Reference</td><td><input type=\"text\" id=\"ref\"></td></tr>\r\n");
      out.write("   <tr><td>Freight</td><td><input type=\"text\" id=\"freight\"></td><td></td><td>Remarks</td><td><input type=\"text\" id=\"remarks\"></td></tr>\r\n");
      out.write("   <tr><td>Payment</td><td><input type=\"text\" id=\"payment\"></td><td>% Advance</td></tr>\r\n");
      out.write("   <tr><td>Price</td><td><input type=\"text\" id=\"price\"></td></tr>\r\n");
      out.write("   <tr><td>Sales Tax</td><td><input type=\"text\" id=\"salesTax\"></td></tr>\r\n");
      out.write("   <tr><td>Validity</td><td><input type=\"text\" id=\"validity\"></td></tr>\r\n");
      out.write("   <tr><td>Notes</td><td><input type=\"text\" id=\"notes\"></td></tr>\r\n");
      out.write("   \r\n");
      out.write("   </table>\r\n");
      out.write("   &nbsp\r\n");
      out.write("   <table border=\"2\" width=\"80%\" id=\"myTable\">\r\n");
      out.write("   <tr><th>SL No</th><th>Part No</th><th>Description</th><th>Make</th><th>Qty</th><th>MOQ</th><th>SPQ</th><th>Lead time</th><th>Unit Price</th></tr>\r\n");
      out.write("   <tr><td><input type=\"text\" value=\"1\" style=\"width:90px\"></td><td><input type=\"text\" class=\"partFill\" style=\"width:180px\"></td><td><input type=\"text\" ></td><td><input type=\"text\" class=\"makeFill\" onfocus=\"populates()\" style=\"width:180px\"></td><td><input type=\"text\" style=\"width:180px\"></td><td><input type=\"text\" style=\"width:150px\"></td><td><input type=\"text\" style=\"width:150px\"></td><td><input type=\"text\" style=\"width:150px\"></td><td><input type=\"text\" style=\"width:150px\"></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("    <input type=\"button\" value=\"Add Row\" onclick=\"addRows()\">\r\n");
      out.write("     <input type=\"button\" value=\"Submit\" onclick=\"sendData()\">\r\n");
      out.write("     <input type=\"button\" value=\"delete Row\" onclick=\"deleteRows()\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"tabs-2\">\r\n");
      out.write("  <div><select>\r\n");
      out.write("  <option value=\"insert\">Insert Customer Details</option>\r\n");
      out.write("  <option value=\"modify\">Modify Cutomer</option>\r\n");
      out.write("  </select></div>\r\n");
      out.write("    <table id=\"details\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td>First Name</td> <td><input type=text id=\"fName\"></td>\r\n");
      out.write("<td>Last Name</td><td><input type=text id=\"lName\"> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Designation</td><td><input type=text id=\"designation\"> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Company Name</td><td><input type=text id=\"companyName\"> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Mobile Number</td><td><input type=text id=\"mobileNum\"> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Division</td><td><input type=text id=\"division\"> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>VAT</td><td><input type=text id=\"vat\"> </td> \r\n");
      out.write("<td>Sales Tax</td><td><input type=text id=\"salesTaxCust\"> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td >Address</td><td colspan=\"15\"><textarea id=\"addressCust\" rows=5 cols=\"52\"></textarea></td> \r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<input type=\"button\" value=\"Submit\" onclick=\"insertCust()\">\r\n");
      out.write("<input type=\"reset\" value=\"Reset\"> \r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"tabs-3\">\r\n");
      out.write("   <table>\r\n");
      out.write("    <tr><td>Make</td><td><input type=\"text\" id=\"make\"></td></tr>\r\n");
      out.write("    <tr><td>Item</td><td><input type=\"text\" id=\"item\"></td></tr>\r\n");
      out.write("    <tr><td>Description</td><td><input type=\"text\" id=\"desc\"></td></tr>\r\n");
      out.write("    <tr><td>MOQ</td><td><input type=\"text\" id=\"moq\"></td></tr>\r\n");
      out.write("    <tr><td>SPQ</td><td><input type=\"text\" id=\"spq\"></td></tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    <input type=\"button\" onclick=\"insertItems()\" value=\"Send\">\r\n");
      out.write("    <input type=\"reset\" value=\"Reset\">\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
